<a href="https://colab.research.google.com/github/Sehajbirsingh/Algorithm-visualizer/blob/master/Lab_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [1]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [2]:
A=np.array([[5,2,3],[6,1,3],[2,4,1]])
print(A)

[[5 2 3]
 [6 1 3]
 [2 4 1]]


In [3]:

B = A[0:2, 0:2]
print(B)


[[5 2]
 [6 1]]


In [4]:
C=A[1:3,1:3]
print(C)

[[1 3]
 [4 1]]


In [5]:
D=np.array([[4,-7,4],[5,6,-1],[-4,2,5]])
print(D)

[[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]


In [7]:
AD = np.dot(A,D)
print(AD)
print('------------')
DA = np.dot(D,A)
print(DA)


[[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]
------------
[[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]


In [15]:
print(det(B))
print(inv(B))


-6.999999999999999
[[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]


In [10]:
print(det(D))
print(np.dot(D,inv(D)))

411.00000000000017
[[ 1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 6.93889390e-17  1.00000000e+00 -5.55111512e-17]
 [-1.38777878e-17 -8.32667268e-17  1.00000000e+00]]


In [20]:


print(np.round(np.dot(D, inv(D))).astype(int))

print(np.round(np.dot( inv(D),D)).astype(int))



[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
